name: adcc
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.7.0
  country_picker: ^2.0.25
  flutter_svg: ^2.0.9
  lottie: ^3.1.3
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  shared_preferences: ^2.2.2
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.0
  flutter_secure_storage: ^9.0.0

  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/svg/
    - assets/lotties/

flutter_native_splash:
  color: "#FFF9EF" # Background color
  android: true
  ios: true
  fullscreen: true
  android_gravity: center
  android_12:
    color: "#FFF9EF"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  # Add padding to prevent logo from being cut off in circular adaptive icon
  # adaptive_icon_padding: 40%
